# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ap_v3_cpp <- function(S0, K, r, q, tt, sigma, steps) {
    .Call(`_apopt_ap_v3_cpp`, S0, K, r, q, tt, sigma, steps)
}

